-- MySQL Script generated by MySQL Workbench
-- Sat Oct  4 17:07:07 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema claire
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `claire` ;
CREATE SCHEMA IF NOT EXISTS `claire` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `claire` ;

-- -----------------------------------------------------
-- Table `claire`.`github_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `claire`.`github_events` ;

CREATE TABLE IF NOT EXISTS `claire`.`github_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repository_url` VARCHAR(2083) NULL,
  `repository_created_at` INT NULL,
  `repository_description` TEXT NULL,
  `repository_forks` INT NULL,
  `repository_size` INT NULL,
  `repository_name` VARCHAR(250) NULL,
  `repository_owner` VARCHAR(250) NULL,
  `repository_open_issues` INT NULL,
  `repository_watchers` INT NULL,
  `repository_pushed_at` INT NULL,
  `actor_attributes_login` VARCHAR(250) NULL,
  `actor_attributes_location` TEXT NULL,
  `created_at` INT NULL,
  `payload_commit_msg` TEXT NULL,
  `url` VARCHAR(2083) NULL,
  `type` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `name` ON `claire`.`github_events` (`repository_name` ASC);

CREATE INDEX `owner` ON `claire`.`github_events` (`repository_owner` ASC);

CREATE INDEX `actor` ON `claire`.`github_events` (`actor_attributes_login` ASC);

CREATE INDEX `type` ON `claire`.`github_events` (`type` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
