-- MySQL Script generated by MySQL Workbench
-- Thu Oct  9 18:31:33 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema claire
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `claire` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `claire` ;

-- -----------------------------------------------------
-- Table `claire`.`github_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `claire`.`github_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `repository_url` VARCHAR(2083) NULL,
  `repository_created_at` VARCHAR(250) NULL,
  `repository_description` TEXT NULL,
  `repository_forks` INT NULL,
  `repository_size` INT NULL,
  `repository_name` VARCHAR(250) NULL,
  `repository_owner` VARCHAR(250) NULL,
  `repository_open_issues` INT NULL,
  `repository_watchers` INT NULL,
  `repository_pushed_at` VARCHAR(250) NULL,
  `actor_attributes_login` VARCHAR(250) NULL,
  `actor_attributes_location` TEXT NULL,
  `created_at` VARCHAR(250) NULL,
  `payload_commit_msg` TEXT NULL,
  `url` VARCHAR(2083) NULL,
  `type` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`repository_name` ASC),
  INDEX `owner` (`repository_owner` ASC),
  INDEX `actor` (`actor_attributes_login` ASC),
  INDEX `type` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `claire`.`github_aggregated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `claire`.`github_aggregated` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `key` VARCHAR(250) NULL,
  `value` INT NULL,
  `period` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
